name: assignment3

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and export
        run: docker build -t assignment3_art
       

      - name: Save Docker image
        run: |
          mkdir -p /tmp/image
          docker save -o /tmp/image/image.tar assignment3_art
        working-directory: ./assignment3Cloud

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: assignment3_art
          path: /tmp/image/image.tar

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Download image and run it in a container
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: assignment3_art

      - name: Load Docker images from previous workflows
        run: docker load --input assignment3_art/image.tar

      - name: Check assignment3_art image is loaded
        run: docker image ls

      - name: Run image in a container
        run: docker run -p8000:8000 assignment3_art &

      - name: Check container is running
        run: docker ps

      # Set up Python and pytest environment
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run pytest tests and upload the results
      - name: Test with pytest
        run: |
          pytest -v test_word.py > test_results.txt
        working-directory: ./assignment3Cloud

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: GH_test_results
          path: ./assignment3Cloud/test_results.txt
